name: Sync fork with upstream

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2:00 AM UTC
  workflow_dispatch:    # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/rajeshrinet/pygl.git
          git fetch upstream

      - name: Merge upstream/master into current branch (main)
        run: |
          git checkout main
          git merge upstream/master --allow-unrelated-histories || true

      - name: Push changes to fork
        run: git push origin main
