name: Installation


on: push


jobs:

  build-and-test:
    name: Install and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pygibbs
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pygibbs
        shell: bash -l {0}
        run: |
          conda activate pygibbs
          make
